APP:
  NAME: echo_shop
  RUNMODE: development # 模式: development, production, staging, test
  Addr: :9000 # 端口
  URL: http://localhost:9000 # 网站地址
  KEY: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5

DB:
  CONNECTION: mysql
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: echo_shop
  USERNAME: root
  PASSWORD: secret
